// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_chirp_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChrip = `-- name: DeleteChrip :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChrip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChrip, id)
	return err
}
